@startuml
'https://plantuml.com/class-diagram
title Classes - Klassendiagramm

class Getraenkeautomat <root> {
+GetraenkUndWechselgeld kaufen(Getraenkewunsch auswahl, Muenze... einzahlung)
+befuelleAutomat()
+entleereAutomat()
}


'WAREN

class Warenbestand <waren> {
+befuelleGetraenkefaecher()
+entleereGetraenkefaecher()
+summeAlleGetraenke()
}

class Getraenkefach <waren> {
fachNummer
getraenk: Getraenk
getraenkeAnzahl
maxGetraenkeAnzahl
preis
+isGetraenkefachLeer()
+isGetraenkefachVoll()
}

class Getraenk <waren> {
name
}


'KASSE

class Geldbestand <kasse> {
+befuelleMuenzfaecher()
+entleereMuenzfaecher()
+summeAlleMuenzen()
+umwandelnBetrat2Muenzen()
+umwandelnMuenzen2Betrag()
+umwandelnBetra2Cents()
+umwandelnCents2Betrag()
}

class Muenzfach <kasse> {
muenze: Muenztyp
muenzenAnzahl
maxMuenzenAnzahl
+isMuenzfachLeer()
+isMuenzfachVoll()
}

class Muenze <kasse> {
muenze: Muenztyp
+getWertInCent()
}


'OHNE_BEZIEHUNG

class GetraenkUndWechselgeld <DTO> {
getraenk: Getraenk
wechselgeld: List<Muenze>
fehler: String
}

class Getraenkewunsch <DTO> {
fachNummer
}

enum Muenztyp <kasse> {
ZEHN_CENT
ZWANZIG_CENT
FUENZIG_CENT
EIN_EURO
ZWEI_EURO
}


'BEZIEHUNGEN
'https://info-wsf.de/assoziation-aggregation-und-komposition/
'https://www.geeksforgeeks.org/association-composition-aggregation-java/
'Komposition
'Class --* Composition
'Aggregation
'Class --o Aggregation
'Assoziation
'Class --> Association
'Class --|> Extension

Getraenkeautomat *-> "1" Warenbestand
Warenbestand -> "1..n" Getraenkefach : ist sortiert in
Getraenkefach -> "0..n" Getraenk : lagert

Getraenkeautomat *--> "1" Geldbestand
Geldbestand --> "5" Muenzfach : ist sortiert in
Muenzfach --> "0..n" Muenze : lagert

@enduml