@startuml
title Classes - Klassendiagramm

class Getraenkeautomat <root> {
+GetraenkUndWechselgeld kaufen(Getraenkewunsch auswahl, Muenze... einzahlung)
+befuelleAutomat()
+entleereAutomat()
}


'WAREN

class Warenbestand <waren> {
+summeAlleGetraenke()
}

class Getraenkefach <waren> {
fachNummer
getraenk: Getraenk
getraenkeAnzahl
maxGetraenkeAnzahl
preis
+isGetraenkefachLeer()
+isGetraenkefachVoll()
}

class Getraenk <waren> {
name
}


'KASSE

class Geldbestand <kasse> {
+summeAlleMuenzen()
+umwandelnBetrat2Muenzen()
+umwandelnMuenzen2Betrag()
+umwandelnBetra2Cents()
+umwandelnCents2Betrag()
}

class Muenzfach <kasse> {
muenze: Muenztyp
MuenzenAnzahl
maxMuenzenAnzahl
+isMuenzfachLeer()
+isMuenzfachVoll()
}

class Muenze <kasse> {
muenze: Muenztyp
werteInCent
}


'OHNE_BEZIEHUNG

class GetraenkUndWechselgeld <DTO> {
getraenk: Getraenk
wechselgeld: List<Muenze>
fehler: String
}

class Getraenkewunsch <DTO> {
fachNummer
}

enum Muenztyp <kasse> {
ZEHN_CENT
ZWANZIG_CENT
FUENZIG_CENT
EIN_EURO
ZWEI_EURO
}


'BEZIEHUNGEN

Getraenkeautomat *-> "1" Warenbestand
Warenbestand -> "1..n" GetraenkeFach
GetraenkeFach -> "0..n" Getraenk

Getraenkeautomat *--> "1" Geldbestand
Geldbestand --> "5" Muenzfach : ist sortiert in
Muenzfach --> "0..n" Muenze : lagert

@enduml