@startuml
'https://plantuml.com/sequence-diagram

autonumber

Start -> Getraenkeautomat: kaufen(auswahl, einzahlung)

Getraenkeautomat -> Warenbetand :  pruefenGetraenkewunschVorhanden(auswahl)

Getraenkeautomat -> Getraenkeautomat : pruefenEinzahlungBetragAusreichend(auswahl,einzahlung)

Getraenkeautomat -> Getraenkeautomat : pruefenMuenzenFuerWechselgeldAusreichend(auswahl,einzahlung)

Getraenkeautomat -> Geldbestand :  befuelleMuenzfaecher(einzahlung)

Getraenkeautomat -> Getraenkeautomat : abziehenMuenzenVonMuenzfaecher(auswahl,einzahlung)

Getraenkeautomat -> Warenbetand :  warenbestand.getraenkAusgeben(auswahl)

Getraenkeautomat <-- Warenbetand :  Getraenk

Getraenkeautomat -> Getraenkeautomat: kaufenErfolgreichAbschliessen(getraenk,wechselgeldMunzen)

Start <-- Getraenkeautomat: GetraenkUndWechselgeld

@enduml
